allowBuilds:
  '@sentry/cli': true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - hookforge-core@0.0.2-canary.23bf755
  - hookforge-nextjs@0.0.2-canary.23bf755
  - hookbase-core@0.0.1 || 0.0.2 || 0.0.3
  - hookbase-nextjs@0.0.1 || 0.0.2 || 0.0.3
