/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'product-library': ProductLibrary;
    products: Product;
    categories: Category;
    inventory: Inventory;
    orders: Order;
    'order-items': OrderItem;
    transactions: Transaction;
    payments: Payment;
    avatars: Avatar;
    'notification-channels': NotificationChannel;
    'product-secrets': ProductSecret;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'product-library': ProductLibrarySelect<false> | ProductLibrarySelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    avatars: AvatarsSelect<false> | AvatarsSelect<true>;
    'notification-channels': NotificationChannelsSelect<false> | NotificationChannelsSelect<true>;
    'product-secrets': ProductSecretsSelect<false> | ProductSecretsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    'connect-telegram': ConnectTelegramWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendWelcomeEmail: TaskSendWelcomeEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('admin' | 'customer') | null;
  /**
   * Customer's full name (used in emails & orders)
   */
  fullName: string;
  avatar?: (number | null) | Avatar;
  /**
   * Optional — useful for SMS notifications or Paystack payments (Nigeria)
   */
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Public profile photos for users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars".
 */
export interface Avatar {
  id: number;
  /**
   * User this profile photo belongs to.
   */
  user: number | User;
  /**
   * User who uploaded this profile photo.
   */
  createdBy: number | User;
  /**
   * User who last updated this profile photo.
   */
  updatedBy?: (number | null) | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Central product image library.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-library".
 */
export interface ProductLibrary {
  id: number;
  /**
   * User who uploaded this file.
   */
  createdBy: number | User;
  /**
   * User who last updated this file.
   */
  updatedBy?: (number | null) | User;
  /**
   * Required for accessibility and SEO. Describe what the image shows.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Products available for purchase. Product type determines fulfillment, while product kind identifies the product category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Product name displayed to customers, e.g. UK 🇬🇧 Lebara SIM.
   */
  name: string;
  /**
   * Customer-facing description of the product and its included features.
   */
  description: string;
  /**
   * Primary image displayed for the product.
   */
  productImage: number | ProductLibrary;
  /**
   * Determines how the product is fulfilled. Physical products require physical delivery; digital products are delivered electronically.
   */
  productType: 'physical' | 'digital';
  /**
   * Product lifecycle status. Inventory availability is determined from stock.
   */
  status: 'active' | 'draft' | 'inactive' | 'archived';
  /**
   * Actual inventory quantity available for fulfillment. This is the authoritative stock value and is updated through inventory movements.
   */
  stock: number;
  /**
   * Customer-facing inventory quantity used for marketing and storefront display. This does not represent the actual inventory available for fulfillment.
   */
  virtualStock: number;
  /**
   * Marketing badges displayed on the product.
   */
  badges?: ('best_seller' | 'coming_soon' | 'featured' | 'new' | 'trending')[] | null;
  /**
   * Current selling price of the product in Nigerian Naira.
   */
  price: number;
  /**
   * Country associated with the product or service.
   */
  country?: string | null;
  /**
   * Category this product belongs to.
   */
  category: number | Category;
  /**
   * URL-friendly identifier generated from the product name.
   */
  slug: string;
  /**
   * Admin who created this product.
   */
  createdBy: number | User;
  /**
   * Admin who last updated this product.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product categories used to organize the TVH product catalog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Human-readable category name.
   */
  name: string;
  /**
   * URL-friendly identifier generated from the category name.
   */
  slug: string;
  /**
   * Optional parent category for nested categories.
   */
  parent?: (number | null) | Category;
  /**
   * Controls whether the category is available to customers.
   */
  status: 'active' | 'inactive';
  /**
   * Admin who created this category.
   */
  createdBy: number | User;
  /**
   * Admin who last updated this category.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable inventory movement history. Current stock is maintained on the product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  /**
   * Product affected by this inventory movement.
   */
  product: number | Product;
  /**
   * Business reason for the inventory quantity change.
   */
  type: 'newstock' | 'restock' | 'sale' | 'return' | 'adjustment' | 'damaged' | 'expired';
  /**
   * Quantity changed by this movement. Positive values increase stock; negative values decrease stock.
   */
  quantity: number;
  /**
   * Product stock immediately before this movement.
   */
  quantityBefore: number;
  /**
   * Product stock immediately after this movement.
   */
  quantityAfter: number;
  /**
   * Optional order, payment, shipment, transaction, or external reference.
   */
  reference?: string | null;
  /**
   * Additional information explaining this inventory movement.
   */
  notes?: string | null;
  /**
   * Admin or system user responsible for this inventory movement.
   */
  createdBy?: (number | null) | User;
  /**
   * Kept for consistency with the audit model. Inventory records cannot be updated.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders and their transaction lifecycle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique customer-facing order number.
   */
  orderNumber: string;
  /**
   * Customer who placed the order.
   */
  buyer: number | User;
  /**
   * Overall lifecycle status of the order.
   */
  orderStatus: 'pending' | 'processing' | 'completed' | 'cancelled' | 'refunded';
  /**
   * Payment status for this order.
   */
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially-refunded' | 'partially-paid';
  /**
   * Currency used for the order.
   */
  currency: 'NGN';
  /**
   * Sum of all order item line totals before shipping and tax.
   */
  subtotal: number;
  /**
   * Total shipping cost charged for the order.
   */
  shippingAmount: number;
  /**
   * Total tax charged for the order.
   */
  taxAmount: number;
  /**
   * Final amount payable by the customer, including shipping and tax.
   */
  total: number;
  /**
   * Customer email captured when the order was placed.
   */
  email: string;
  /**
   * Customer phone number captured when the order was placed.
   */
  phone?: string | null;
  /**
   * Shipping information captured when the order was placed.
   */
  shippingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    state: string;
    postalCode?: string | null;
    country: string;
  };
  /**
   * Customer-provided instructions concerning delivery.
   */
  deliveryInstructions?: string | null;
  /**
   * Internal administrative notes. Never expose these to customers.
   */
  internalNotes?: string | null;
  /**
   * User responsible for creating the order.
   */
  createdBy?: (number | null) | User;
  /**
   * User responsible for the most recent order update.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable snapshots of products purchased as part of an order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  /**
   * Order this item belongs to.
   */
  order: number | Order;
  /**
   * Original product purchased. Historical snapshot fields remain authoritative for this order item.
   */
  product: number | Product;
  /**
   * Product name captured at the time of purchase.
   */
  productName: string;
  /**
   * Product type captured at the time of purchase.
   */
  productType: 'physical' | 'digital';
  /**
   * Product image associated with the product at purchase time.
   */
  productImage?: (number | null) | ProductLibrary;
  /**
   * Unit price captured at the time of purchase.
   */
  unitPrice: number;
  /**
   * Quantity purchased.
   */
  quantity: number;
  /**
   * Final amount charged for this order item.
   */
  lineTotal: number;
  /**
   * Overall lifecycle status of the order.
   */
  orderStatus: 'pending' | 'processing' | 'completed' | 'cancelled' | 'refunded';
  /**
   * Additional purchase-specific data required for fulfillment. Do not store inventory state here.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable financial transaction history for orders and payments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Unique internal transaction reference.
   */
  reference: string;
  /**
   * Order associated with this financial transaction.
   */
  order: number | Order;
  /**
   * Customer associated with the transaction.
   */
  customer: number | User;
  /**
   * Financial event represented by this transaction.
   */
  type: 'payment' | 'refund' | 'chargeback';
  /**
   * Current processing state of this transaction.
   */
  status: 'pending' | 'successful' | 'failed' | 'cancelled';
  /**
   * Transaction amount stored in the smallest currency unit.
   */
  amount: number;
  /**
   * Currency used for this transaction.
   */
  currency: 'NGN';
  /**
   * Payment provider responsible for processing the transaction.
   */
  provider: 'transactpay';
  /**
   * Reference supplied by the payment provider.
   */
  providerReference?: string | null;
  /**
   * Raw or normalized response data received from the payment provider.
   */
  providerResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Original transaction associated with a refund or chargeback.
   */
  parentTransaction?: (number | null) | Transaction;
  /**
   * Payment provider failure code, if available.
   */
  failureCode?: string | null;
  /**
   * Payment provider failure message, if available.
   */
  failureMessage?: string | null;
  /**
   * Human-readable explanation of the transaction.
   */
  description?: string | null;
  /**
   * Admin or system user responsible for creating this transaction.
   */
  createdBy?: (number | null) | User;
  /**
   * Kept for audit consistency. Transactions cannot be updated.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  orderReference: string;
  /**
   * URL used by the customer to complete the payment.
   */
  checkoutUrl?: string | null;
  /**
   * Reference assigned to the payment by the payment provider.
   */
  providerReference?: string | null;
  /**
   * Processing Fee
   */
  providerFee?: number | null;
  totalAmountCharged?: number | null;
  order: number | Order;
  buyer: number | User;
  /**
   * Amount in the smallest currency unit (kobo).
   */
  amount: number;
  currency: 'NGN';
  provider: 'transactpay';
  status: 'pending' | 'successful' | 'failed' | 'partially-paid' | 'refunded' | 'partially-refunded';
  paidAt?: string | null;
  refundedAt?: string | null;
  /**
   * Additional payment information that does not belong to the core payment model.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-channels".
 */
export interface NotificationChannel {
  id: number;
  admin: number | User;
  provider: 'telegram';
  destination: string;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sensitive secrets for digital products. Only administrators can manage secrets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-secrets".
 */
export interface ProductSecret {
  id: number;
  /**
   * Sensitive product secret visible only to authorized administrators or the purchasing buyer.
   */
  secret: string;
  /**
   * Product associated with this secret.
   */
  product: number | Product;
  /**
   * Customer associated with this product purchase.
   */
  buyer?: (number | null) | User;
  /**
   * Admin who created this product secret.
   */
  createdBy: number | User;
  /**
   * Admin who last updated this product secret.
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendWelcomeEmail';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendWelcomeEmail') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'product-library';
        value: number | ProductLibrary;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'avatars';
        value: number | Avatar;
      } | null)
    | ({
        relationTo: 'notification-channels';
        value: number | NotificationChannel;
      } | null)
    | ({
        relationTo: 'product-secrets';
        value: number | ProductSecret;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  avatar?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-library_select".
 */
export interface ProductLibrarySelect<T extends boolean = true> {
  createdBy?: T;
  updatedBy?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  productImage?: T;
  productType?: T;
  status?: T;
  stock?: T;
  virtualStock?: T;
  badges?: T;
  price?: T;
  country?: T;
  category?: T;
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  product?: T;
  type?: T;
  quantity?: T;
  quantityBefore?: T;
  quantityAfter?: T;
  reference?: T;
  notes?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  buyer?: T;
  orderStatus?: T;
  paymentStatus?: T;
  currency?: T;
  subtotal?: T;
  shippingAmount?: T;
  taxAmount?: T;
  total?: T;
  email?: T;
  phone?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  deliveryInstructions?: T;
  internalNotes?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  productName?: T;
  productType?: T;
  productImage?: T;
  unitPrice?: T;
  quantity?: T;
  lineTotal?: T;
  orderStatus?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  reference?: T;
  order?: T;
  customer?: T;
  type?: T;
  status?: T;
  amount?: T;
  currency?: T;
  provider?: T;
  providerReference?: T;
  providerResponse?: T;
  parentTransaction?: T;
  failureCode?: T;
  failureMessage?: T;
  description?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  orderReference?: T;
  checkoutUrl?: T;
  providerReference?: T;
  providerFee?: T;
  totalAmountCharged?: T;
  order?: T;
  buyer?: T;
  amount?: T;
  currency?: T;
  provider?: T;
  status?: T;
  paidAt?: T;
  refundedAt?: T;
  metadata?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars_select".
 */
export interface AvatarsSelect<T extends boolean = true> {
  user?: T;
  createdBy?: T;
  updatedBy?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-channels_select".
 */
export interface NotificationChannelsSelect<T extends boolean = true> {
  admin?: T;
  provider?: T;
  destination?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-secrets_select".
 */
export interface ProductSecretsSelect<T extends boolean = true> {
  secret?: T;
  product?: T;
  buyer?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connect-telegram_widget".
 */
export interface ConnectTelegramWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendWelcomeEmail".
 */
export interface TaskSendWelcomeEmail {
  input: {
    userEmail: string;
    userFullname: string;
  };
  output: {
    success: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}